// Package token implements HMAC-SHA256 token generation and verification
// for Unsample debug trace authentication.
//
// Token format: <trace_id>:<unix_timestamp>:<hmac_base64url>
//
// The token is generated by the CLI and verified by both the SDK interceptor
// and the Collector processor. A shared secret must be configured in all
// three components.
//
// Tokens are time-bound (default 2 hours) to prevent replay attacks.
package token

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
	"time"
)

const (
	// DefaultMaxAge is the default token expiry duration.
	DefaultMaxAge = 2 * time.Hour

	// tokenParts is the expected number of parts in a token string.
	tokenParts = 3

	// separator is the delimiter between token components.
	separator = ":"
)

// Generate creates a signed debug token for the given trace ID.
// The token includes the trace ID, current timestamp, and an HMAC-SHA256
// signature that can be verified by any component sharing the same secret.
func Generate(secret, traceID string) string {
	timestamp := time.Now().Unix()
	payload := traceID + separator + strconv.FormatInt(timestamp, 10)

	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(payload))
	sig := base64.URLEncoding.EncodeToString(mac.Sum(nil))

	return fmt.Sprintf("%s%s%d%s%s", traceID, separator, timestamp, separator, sig)
}

// GenerateWithTimestamp creates a signed debug token with a specific timestamp.
// This is primarily useful for testing.
func GenerateWithTimestamp(secret, traceID string, timestamp int64) string {
	payload := traceID + separator + strconv.FormatInt(timestamp, 10)

	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(payload))
	sig := base64.URLEncoding.EncodeToString(mac.Sum(nil))

	return fmt.Sprintf("%s%s%d%s%s", traceID, separator, timestamp, separator, sig)
}

// Verify checks that the token is valid: correctly signed and not expired.
// It returns true only if the HMAC signature matches and the token age
// is within maxAge.
func Verify(tokenStr, secret string, maxAge time.Duration) bool {
	traceID, timestamp, sig, ok := parse(tokenStr)
	if !ok {
		return false
	}

	// Check expiry
	tokenTime := time.Unix(timestamp, 0)
	if time.Since(tokenTime) > maxAge {
		return false
	}

	// Check that the token is not from the future (clock skew tolerance: 1 min)
	if tokenTime.After(time.Now().Add(1 * time.Minute)) {
		return false
	}

	// Verify HMAC
	payload := traceID + separator + strconv.FormatInt(timestamp, 10)
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(payload))
	expected := base64.URLEncoding.EncodeToString(mac.Sum(nil))

	return hmac.Equal([]byte(sig), []byte(expected))
}

// ExtractTraceID extracts the trace ID from a token string without
// verifying the signature. Returns empty string if the token is malformed.
func ExtractTraceID(tokenStr string) string {
	traceID, _, _, ok := parse(tokenStr)
	if !ok {
		return ""
	}
	return traceID
}

// parse splits a token string into its components.
func parse(tokenStr string) (traceID string, timestamp int64, sig string, ok bool) {
	parts := strings.SplitN(tokenStr, separator, tokenParts)
	if len(parts) != tokenParts {
		return "", 0, "", false
	}

	traceID = parts[0]
	if traceID == "" {
		return "", 0, "", false
	}

	ts, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil {
		return "", 0, "", false
	}

	sig = parts[2]
	if sig == "" {
		return "", 0, "", false
	}

	return traceID, ts, sig, true
}
